### ISSUE TITLE
Waipy import error

### ISSUE THREAD

**Issue by chayanroyc** [mabelcalim/waipy#22]
When I wrote import waipy, I get the following error:
Traceback (most recent call last):
  File "C:\Users\acer\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-950-621b99ac5fff>", line 1, in <module>

**Comment by mabelcalim** [comment]
python3 fixed at #19
