### ISSUE TITLE
one bug in waipy.cwt

### ISSUE THREAD

**Issue by lovechang1986** [mabelcalim/waipy#5]
i used the code example in notebook :Example 1 Sine and Waipy ,some bug attacked.
while the wavelet analysis in matlab code, there is not a name parameter?

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-c503cffc06b5> in <module>()
      9 
     10 data_norm = waipy.normalize(x)
---> 11 result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72, 6, mother='Morlet',name='x')
     12 waipy.wavelet_plot('Sine', z, data_norm, 0.03125, result)
     13 

C:\Anaconda2\lib\site-packages\waipy-0.0.9.0-py2.7.egg\waipy\cwt\wavetest.pyc in cwt(data, dt, pad, dj, s0, j1, lag1, param, mother, name)
     86     # Wavelet transform
     87     ondaleta, wave, period, scale, coi, f = lib_wavelet.wavelet(
---> 88         data, dt, param, dj, s0, j1, mother)
     89     # wave = np.array(wave)
     90     power = (np.abs(wave) ** 2)

C:\Anaconda2\lib\site-packages\waipy-0.0.9.0-py2.7.egg\waipy\cwt\lib_wavelet.pyc in wavelet(Y, dt, param, dj, s0, j1, mother)
    170         # delete the first value of k_neg = last value of k_pos
    171         k_neg = k_neg[1:-1]
--> 172     k = np.concatenate((k_pos, k_neg), axis=1)  # vector of symmetric
    173     # compute fft of the padded time series
    174     f = np.fft.fft(x, n)

IndexError: axis 1 out of bounds [0, 1)

**Comment by mabelcalim** [comment]
Hi

Your waipy needs an upgrade!  :D
You have an old version. Try to download the new version from github (
https://github.com/mabelcalim/waipy).

cheers

Mabel

------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by lovechang1986** [comment]
THK, 
i already download the new version waipy-0.09, but the bug still exist.


pip install waipy:
Requirement already satisfied (use --upgrade to upgrade): waipy in c:\anaconda2\lib\site-packages\waipy-0.0.9.0-py2.7.eg

**Comment by mabelcalim** [comment]
Hi

The pip version of waipy don't have the changes that the version of the
github has.
So, I strongly suggest that you follow the instructions to download the git
version  (https://github.com/mabelcalim/waipy).
Then the examples will work just fine.

cheers
Mabel

------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by lovechang1986** [comment]
hi,
I according to your suggestion, download the zip from github,and use "python setup.py install".
so i asked again.
and my python enviroment: python2.7.9, win7 64-bit.
Did the python3 work or other error?

**Comment by lovechang1986** [comment]
hi,
one suggestion:
in matlab :   std(var) , use the DOF = (n - 1) standard deviation
but in numpy: np.std or np.var ,use the DOF = n standard deviation.

**Comment by brunofisico** [comment]
Hello, how are you? I am having the same problem in waipy functionality. I did the footsteps of his tutorial and nothing ...

**Comment by mabelcalim** [comment]
Hi Bruno

Hi

The pip version of waipy don't have the changes that the version of the
github has.
So, I strongly suggest that you follow the instructions to download the git
version  (https://github.com/mabelcalim/waipy).
Then the examples will work just fine.

cheers

Ps: it's HER tutorial. .. I'm a woman ;)

•••

Em 13h00 Sáb, 30/07/2016, brunofisico <notifications@github.com> escreveu:

**Comment by brunofisico** [comment]
Mil perdões, Mabel...rsrsr

vou ver agora.

grato.


Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-07-31 9:22 GMT-03:00 Mabel <notifications@github.com>:

**Comment by brunofisico** [comment]
fiz como sugeriu, veja a saída...me dá uma força ai


Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-07-31 9:26 GMT-03:00 Bruno Lustosa <bruno.moura.pesquisa@gmail.com>:

**Comment by mabelcalim** [comment]
Bruno

You still using the pip version. Try to uninstall the pip version, and
install the git version.

If you have any trouble, send me the error.

Cheers

------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by brunofisico** [comment]
hello Mabel

It really was before the pip package but now did everything right as your
tutorial page. There are two notable errors: The first when it includes
 'name' in the result and the second without it. Follow the pictures


---------------------------------------------------------------------------TypeError
                                Traceback (most recent call
last)<ipython-input-6-b835d1ad58f7> in <module>()      9 data_norm1 =
waipy.normalize(y2)     10 ---> 11 result = waipy.cwt(data_norm, 1, 1,
0.25, 2, 4/0.25, 0.72, 6, mother='Morlet', name='x')     12 result1 =
waipy.cwt(data_norm1, 1, 1, 0.25, 2, 4/0.25, 0.72, 6,mother='Morlet',
name='y')     13
TypeError: cwt() got an unexpected keyword argument 'name'






---------------------------------------------------------------------------IndexError
                               Traceback (most recent call
last)<ipython-input-7-dfb6186ff4de> in <module>()      9 data_norm1 =
waipy.normalize(y2)     10 ---> 11 result = waipy.cwt(data_norm, 1, 1,
0.25, 2, 4/0.25, 0.72, 6, mother='Morlet')     12 result1 =
waipy.cwt(data_norm1, 1, 1, 0.25, 2, 4/0.25, 0.72, 6,mother='Morlet')
   13
/home/bruno/anaconda2/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg/waipy/cwt/wavetest.pyc
in cwt(data, dt, pad, dj, s0, j1, lag1, param, mother)     73
# Wavelet transform     74         import lib_wavelet---> 75
ondaleta,wave,period,scale,coi,f =
lib_wavelet.wavelet(data,dt,mother,param)#,pad,dj,s0,j1,mother,param)
   76         power = np.abs(wave*wave)     77         # Significance
levels: (variance=1 for the normalized SST)
/home/bruno/anaconda2/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg/waipy/cwt/lib_wavelet.pyc
in wavelet(Y, dt, mother, param)    130                 k_neg = [e *
(-1) for e in k_neg]                       # negative part    131
           k_neg = k_neg[1:-1]                                     #
delete the first value of k_neg = last value of k_pos--> 132         k
= np.concatenate((k_pos,k_neg), axis =1)                      # vector
of symmetric    133         # compute fft of the padded time series
134         f = np.fft.fft(x,n)
IndexError: axis 1 out of bounds [0, 1)






Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-08-05 14:45 GMT-03:00 Mabel <notifications@github.com>:

**Comment by mabelcalim** [comment]
Hi Bruno,
You still using the pip version:
home/bruno/anaconda2/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg/waipy/cwt/wavetest.pyc
Try : pip uninstall waipy
And then install the git version.

The examples are working just fine.  I think the pip version doesn't have
name option and the github version has.

Em 11h37 Sáb, 06/08/2016, Bruno Lustosa de Moura <notifications@github.com>
escreveu:

**Comment by mabelcalim** [comment]
Bruno, if you still have some trouble, we can arrange a hangout and I help
you to install it.

------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by brunofisico** [comment]
ok when you can'm here ... I do not really know how to proceed.



Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-08-06 18:43 GMT-03:00 Mabel <notifications@github.com>:

> Bruno, if you still have some trouble, we can arrange a hangout and I help
> you to install it.
>
> ------------------------------------------------------------------------
>
> *Mabel Calim Costa*
> Instituto Nacional de Pesquisas Espaciais - INPE
> Cachoeira Paulista -SP
> +55 (12) 3186 - 8566 (ramal *8566*)
> -------------------------------------------------------------------------
>
>

**Comment by mabelcalim** [comment]
Hi all,

I'll need more time to update the pip version of waipy, so, please use the
git version!

I've just tested the git version, and for me is working just fine.
Some cookbook to use this version ( Example 1 of github):

open a terminal:

> git clone https://github.com/mabelcalim/waipy.git

> cd waipy/

> sudo python setup.py install


> python

>>>  import waipy

>>>  import numpy as np

>>>  import matplotlib.pyplot as pet

>>>  import pylab

>>>  z = np.linspace(0,2048,2048)

>>>  x = np.sin(50*np.pi*z)

>>>  y = np.cos(50*np.pi*z)

>>>  data_norm = waipy.normalize(x)


>>>  result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72,
6,mother='Morlet',name='x')

>>>  waipy.wavelet_plot('Sine', z, data_norm, 0.03125, result)

>>>  pylab.show()


>>> data_norm1 = waipy.normalize(y)

>>> result1 = waipy.cwt(data_norm1, 1, 1, 0.125, 2, 4/0.125, 0.72, 6,

...                     mother='Morlet',name='y')

>>> waipy.wavelet_plot('Cosine', z, data_norm1, 0.03125, result1)

>>> pylab.show()


>>> cross_power, coherence, phase_angle =
waipy.cross_wavelet(result['wave'],

...
result1['wave'])

>>> waipy.plot_cross('Crosspower sine and cosine', cross_power, phase_angle,

...                  z, result, result1)

>>> pylab.show()



The figures can look better in ipython notebook ;)

In time I'll improve the examples with more info and images.



Have fun with waipy !!!

Cheers

Mabel






------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by brunofisico** [comment]
segue o erro....


Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-08-09 21:16 GMT-03:00 Mabel <notifications@github.com>:

**Comment by mabelcalim** [comment]
Hi Bruno,

Did you try the tutorial of my previous message?
Please add your error from the previous tutorial

thanks


------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------


On 10 August 2016 at 10:58, Bruno Lustosa de Moura <notifications@github.com

**Comment by brunofisico** [comment]
Sim, segui perfeitamente o seu tutorial, deu certo a instalação do waipy
mas não funciona quando coloco "result'



IndentationError: unexpected indent
>>> import pylab
>>> z = np.linspace(0,2048,2048)
>>> x = np.sin(50*np.pi*z)
>>> y = np.cos(50*np.pi*z)
>>> data_norm = waipy.normalize(x)
>>> result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72,
... 6,mother='Morlet',name='x')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/waipy/cwt/wavetest.py", line 88, in cwt
  File "build/bdist.linux-x86_64/egg/waipy/cwt/lib_wavelet.py", line 172,
in wavelet
IndexError: axis 1 out of bounds [0, 1)
>>>




Att,
----------------------------------------------------------------------------------------------------------------------------------------------------------
*Bruno Lustosa de Moura*
Instituto Federal de Ciência e Tecnologia do R.G do Norte - IFRN
+55 84 99991-9550
Mestre em Astrofísica
Aluno de Doutorado em Física - UFRN
Grupo de Estutura e Evolução Estelar - GE3
http://astro.dfte.ufrn.br/
----------------------------------------------------------------------------------------------------------------------------------------------------------
"Pois, quando eu me sinto fraco, é então que sou forte..."
(2Cor 12,10)


2016-08-10 11:23 GMT-03:00 Mabel <notifications@github.com>:

**Comment by gavin971** [comment]
import waipy
import numpy as np
import matplotlib.pyplot as pet
import pylab
z = np.linspace(0,2048,2048)
x = np.sin(50*np.pi*z)
y = np.cos(50*np.pi*z)
data_norm = waipy.normalize(x)
result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72,6,mother='Morlet',name='x')
waipy.wavelet_plot('Sine', z, data_norm, 0.03125, result)
pylab.show()

data_norm1 = waipy.normalize(y)
result1 = waipy.cwt(data_norm1, 1, 1, 0.125, 2, 4/0.125, 0.72, 6,mother='Morlet',name='y')
waipy.wavelet_plot('Cosine', z, data_norm1, 0.03125, result1)
pylab.show()
cross_power, coherence, phase_angle =waipy.cross_wavelet(result['wave'],result1['wave'])
waipy.plot_cross('Crosspower sine and cosine', cross_power,phase_angle,z, result, result1)
pylab.show()


**Traceback (most recent call last):
  File "/Users/fuzhp/Downloads/Python_Library/waipy_file/waipy/Waipy Examples /tewt.py", line 9, in <module>
    result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72,6,mother='Morlet',name='x')
  File "build/bdist.macosx-10.6-x86_64/egg/waipy/cwt/wavetest.py", line 88, in cwt
  File "build/bdist.macosx-10.6-x86_64/egg/waipy/cwt/lib_wavelet.py", line 172, in wavelet
IndexError: axis 1 out of bounds [0, 1)
[Finished in 1.598s]**

**Comment by gavin971** [comment]
**I modify the  "axis=1" with "axis=0"  ( lib_wavelet.py and wavetest.py), just get the following warning. Besides, I can  run the example(https://wavelet-analysis.readthedocs.io/en/latest/cookbook.html) successfully, and plot the data nino3. (the graph attachment** **https://www.dropbox.com/s/o861f36bxi67306/figure_1.png?dl=0** )

/Users/fuzhp/anaconda/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg/waipy/cwt/wavetest.py:88: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/fuzhp/anaconda/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg/waipy/cwt/wavetest.py:89: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

**Comment by WUhailing** [comment]
Same bug occurred in python 2.7 windows10, line 172 k = np.concatenate((k_pos, k_neg), axis=1)  axis 1 out of bounds [0, 1), then I modify the "axis=1" with "axis=0" ( lib_wavelet.py and wavetest.py),  but it is still not working and return same error. I downloaded the zip folder from github, extract waipy.zip under site-packages, **python setup.pyinstall**  and import waipy.

**Comment by mabelcalim** [comment]
Hi WUhailing

Please don' try to unzip waipy under site-packages directory, this is not
how it works.
You have 2 options:
1) Install in your local machine:

download the zip file
unzip waipy in your home : /usr/home/
$cd waipy
$python setup.py install


2) clone from github:

open a terminal:

> git clone https://github.com/mabelcalim/waipy.git

> cd waipy/

> sudo python setup.py install


If you still having problems to install, I suggest that you use the git for
windows (https://git-for-windows.github.io/).


Please let me know if you still have problems to install waipy

Good luck!




ps: if you succeed, try this example


> python

>>>  import waipy

>>>  import numpy as np

>>>  import matplotlib.pyplot as pet

>>>  import pylab

>>>  z = np.linspace(0,2048,2048)

>>>  x = np.sin(50*np.pi*z)

>>>  y = np.cos(50*np.pi*z)

>>>  data_norm = waipy.normalize(x)


>>>  result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72,
6,mother='Morlet',name='x')

>>>  waipy.wavelet_plot('Sine', z, data_norm, 0.03125, result)

>>>  pylab.show()


>>> data_norm1 = waipy.normalize(y)

>>> result1 = waipy.cwt(data_norm1, 1, 1, 0.125, 2, 4/0.125, 0.72, 6,

...                     mother='Morlet',name='y')

>>> waipy.wavelet_plot('Cosine', z, data_norm1, 0.03125, result1)

>>> pylab.show()


>>> cross_power, coherence, phase_angle = waipy.cross_wavelet(result['wa
ve'],

...
result1['wave'])

>>> waipy.plot_cross('Crosspower sine and cosine', cross_power, phase_angle,

...                  z, result, result1)

>>> pylab.show()

Have fun with waipy !!!

Cheers
------------------------------------------------------------------------

*Mabel Calim Costa*
Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8566 (ramal *8566*)
-------------------------------------------------------------------------

**Comment by WUhailing** [comment]
Hi Mabel,
Option 1 can install Waipy, but same error still exists. Option 2 cannot install, I opened Git installed on Windows10, and do git clone Waipy,  then find out sudo is not recognized on Windows.

**Comment by macoj** [comment]
Dear all, the same occurs here. 

The following steps allow you to reproduce the bug:

1. Downloading and installing:
```bash
[marcos@arch ~/Downloads]$ git clone https://github.com/mabelcalim/waipy.git
Cloning into 'waipy'...
remote: Counting objects: 684, done.
remote: Total 684 (delta 0), reused 0 (delta 0), pack-reused 684
Receiving objects: 100% (684/684), 14.00 MiB | 8.86 MiB/s, done.
Resolving deltas: 100% (194/194), done.
[marcos@arch ~/Downloads]$ cd waipy/
[marcos@arch ~/Downloads/waipy]$ python2.7 setup.py build 
running build
running build_py
creating build
creating build/lib
creating build/lib/waipy
copying lib/waipy/mainmodule.py -> build/lib/waipy
copying lib/waipy/__init__.py -> build/lib/waipy
creating build/lib/waipy/cwt
copying lib/waipy/cwt/wavetest.py -> build/lib/waipy/cwt
copying lib/waipy/cwt/lib_wavelet.py -> build/lib/waipy/cwt
copying lib/waipy/cwt/__init__.py -> build/lib/waipy/cwt
creating build/lib/waipy/cwa
copying lib/waipy/cwa/cross_wavelet.py -> build/lib/waipy/cwa
copying lib/waipy/cwa/__init__.py -> build/lib/waipy/cwa
[marcos@arch ~/Downloads/waipy]$ sudo python2.7 setup.py install 
running install
running bdist_egg
running egg_info
writing lib/waipy.egg-info/PKG-INFO
writing top-level names to lib/waipy.egg-info/top_level.txt
writing dependency_links to lib/waipy.egg-info/dependency_links.txt
reading manifest file 'lib/waipy.egg-info/SOURCES.txt'
writing manifest file 'lib/waipy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/waipy
copying build/lib/waipy/mainmodule.py -> build/bdist.linux-x86_64/egg/waipy
creating build/bdist.linux-x86_64/egg/waipy/cwt
copying build/lib/waipy/cwt/wavetest.py -> build/bdist.linux-x86_64/egg/waipy/cwt
copying build/lib/waipy/cwt/lib_wavelet.py -> build/bdist.linux-x86_64/egg/waipy/cwt
copying build/lib/waipy/cwt/__init__.py -> build/bdist.linux-x86_64/egg/waipy/cwt
copying build/lib/waipy/__init__.py -> build/bdist.linux-x86_64/egg/waipy
creating build/bdist.linux-x86_64/egg/waipy/cwa
copying build/lib/waipy/cwa/cross_wavelet.py -> build/bdist.linux-x86_64/egg/waipy/cwa
copying build/lib/waipy/cwa/__init__.py -> build/bdist.linux-x86_64/egg/waipy/cwa
byte-compiling build/bdist.linux-x86_64/egg/waipy/mainmodule.py to mainmodule.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/cwt/wavetest.py to wavetest.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/cwt/lib_wavelet.py to lib_wavelet.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/cwt/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/cwa/cross_wavelet.py to cross_wavelet.pyc
byte-compiling build/bdist.linux-x86_64/egg/waipy/cwa/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/waipy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/waipy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/waipy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/waipy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/waipy-0.0.9.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing waipy-0.0.9.0-py2.7.egg
Copying waipy-0.0.9.0-py2.7.egg to /usr/lib/python2.7/site-packages
Adding waipy 0.0.9.0 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/waipy-0.0.9.0-py2.7.egg
Processing dependencies for waipy==0.0.9.0
Finished processing dependencies for waipy==0.0.9.0
[marcos@arch ~/Downloads/waipy]$ 
```

2. Testing example 1:
```python
[marcos@arch ~/Downloads/waipy]$ python2.7 
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import waipy
>>> import numpy as np
>>> z = np.linspace(0, 2048, 2048)
>>> x = np.sin(50*np.pi*z)
>>> y = np.cos(50*np.pi*z)
>>> data_norm = waipy.normalize(x)
>>> result = waipy.cwt(data_norm, 1, 1, 0.125, 2, 4/0.125, 0.72, 6, mother='Morlet', name='y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/waipy/cwt/wavetest.py", line 88, in cwt
  File "build/bdist.linux-x86_64/egg/waipy/cwt/lib_wavelet.py", line 172, in wavelet
IndexError: axis 1 out of bounds [0, 1)
>>> 
```

The versions of the libraries in machine are following:
```python
>>> numpy.__version__
'1.12.0'
>>> netCDF4.__version__
'1.2.7'
>>> matplotlib.__version__ 
'1.5.2'
```

And the version of python is:
```bash
[marcos@arch ~/Downloads/waipy]$ python2.7 --version
Python 2.7.12
```

**Comment by mabelcalim** [comment]
Hi Marcos,  are you using windows?  I suggest that you clone waipy in a
workdir in your $ home  and use the pyrhon from your system ( probably
other 2.7 version ).

Em 9:20PM Ter, 07/03/2017, Marcos Oliveira <notifications@github.com>
escreveu:

**Comment by macoj** [comment]
Hi Mabel, I am on Arch Linux. Here I have only one version of python2.7. I wonder if this is not a problem with newer versions of numpy. 

Marcos

**Comment by mabelcalim** [comment]
Hi!
Yesterday I converted waipy to python3.6. Now it's waipy0.0.1.0!
Try to check the example_python3.6 on my github (https://github.com/mabelcalim/waipy)

I hardly recommend to install from github:
in your path:
git clone https://github.com/mabelcalim/waipy.git
cd waipy
python3 setup.py install

And try to use the example ;)
If you have some problem to install, please let me know!

Thanks for choosing waipy!
Best regards
Mabel
